## D209 - Task 1

In [41]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler, OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
oe = OrdinalEncoder(handle_unknown='ignore')

pd.options.display.float_format = '{:.5f}'.format
pd.options.display.max_columns = None

In [42]:
data = pd.read_csv('medical_clean.csv')

In [43]:
data

,CaseOrder,Customer_id,Interaction,UID,City,State,County,Zip,Lat,Lng,Population,Area,TimeZone,Job,Children,Age,Income,Marital,Gender,ReAdmis,VitD_levels,Doc_visits,Full_meals_eaten,vitD_supp,Soft_drink,Initial_admin,HighBlood,Stroke,Complication_risk,Overweight,Arthritis,Diabetes,Hyperlipidemia,BackPain,Anxiety,Allergic_rhinitis,Reflux_esophagitis,Asthma,Services,Initial_days,TotalCharge,Additional_charges,item1,item2,item3,item4,item5,item6,item7,item8
0,1,C412403,8cd49b13-f45a-4b47-a2bd-173ffa932c2f,3a83ddb66e2ae73798bdf1d705dc0932,Eva,AL,Morgan,35621,34.34960,-86.72508,2951,Suburban,America/Chicago,"Psychologist, sport and exercise",1,53,86575.93000,Divorced,Male,No,19.14147,6,0,0,No,Emergency Admission,Yes,No,Medium,No,Yes,Yes,No,Yes,Yes,Yes,No,Yes,Blood Work,10.58577,3726.70286,17939.40342,3,3,2,2,4,3,3,4
1,2,Z919181,d2450b70-0337-4406-bdbb-bc1037f1734c,176354c5eef714957d486009feabf195,Marianna,FL,Jackson,32446,30.84513,-85.22907,11303,Urban,America/Chicago,Community development worker,3,51,46805.99000,Married,Female,No,18.94035,4,2,1,No,Emergency Admission,Yes,No,High,Yes,No,No,No,No,No,No,Yes,No,Intravenous,15.12956,4193.19046,17612.99812,3,4,3,4,4,4,3,3
2,3,F995323,a2057123-abf5-4a2c-abad-8ffe33512562,e19a0fa00aeda885b8a436757e889bc9,Sioux Falls,SD,Minnehaha,57110,43.54321,-96.63772,17125,Suburban,America/Chicago,Chief Executive Officer,3,53,14370.14000,Widowed,Female,No,18.05751,4,1,0,No,Elective Admission,Yes,No,Medium,Yes,No,Yes,No,No,No,No,No,No,Blood Work,4.77218,2434.23422,17505.19246,2,4,4,4,3,4,3,3
3,4,A879973,1dec528d-eb34-4079-adce-0d7a40e82205,cd17d7b6d152cb6f23957346d11c3f07,New Richland,MN,Waseca,56072,43.89744,-93.51479,2162,Suburban,America/Chicago,Early years teacher,0,78,39741.49000,Married,Male,No,16.57686,4,1,0,No,Elective Admission,No,Yes,Medium,No,Yes,No,No,No,No,No,Yes,Yes,Blood Work,1.71488,2127.83042,12993.43735,3,5,5,3,4,5,5,5
4,5,C544523,5885f56b-d6da-43a3-8760-83583af94266,d2f0425877b10ed6bb381f3e2579424a,West Point,VA,King William,23181,37.59894,-76.88958,5287,Rural,America/New_York,Health promotion specialist,1,22,1209.56000,Widowed,Female,No,17.43907,5,0,2,Yes,Elective Admission,No,No,Low,No,No,No,Yes,No,No,Yes,No,No,CT Scan,1.25481,2113.07327,3716.52579,2,1,3,3,5,3,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,B863060,a25b594d-0328-486f-a9b9-0567eb0f9723,39184dc28cc038871912ccc4500049e5,Norlina,NC,Warren,27563,36.42886,-78.23716,4762,Urban,America/New_York,"Programmer, multimedia",2,25,45967.61000,Widowed,Male,No,16.98086,4,2,1,No,Emergency Admission,Yes,No,Medium,No,No,No,No,No,Yes,No,Yes,No,Intravenous,51.56122,6850.94200,8927.64200,3,2,2,3,4,3,4,2
9996,9997,P712040,70711574-f7b1-4a17-b15f-48c54564b70f,3cd124ccd43147404292e883bf9ec55c,Milmay,NJ,Atlantic,8340,39.43609,-74.87302,1251,Urban,America/New_York,"Restaurant manager, fast food",4,87,14983.02000,Widowed,Male,Yes,18.17702,5,0,0,No,Elective Admission,Yes,No,Medium,Yes,Yes,Yes,No,No,No,No,No,Yes,CT Scan,68.66824,7741.69000,28507.15000,3,3,4,2,5,3,4,4
9997,9998,R778890,1d79569d-8e0f-4180-a207-d67ee4527d26,41b770aeee97a5b9e7f69c906a8119d7,Southside,TN,Montgomery,37171,36.36655,-87.29988,532,Rural,America/Chicago,"Psychologist, occupational",3,45,65917.81000,Separated,Female,Yes,17.12907,4,2,0,Yes,Elective Admission,Yes,No,High,Yes,No,No,No,No,Yes,Yes,No,No,Intravenous,70.15418,8276.48100,15281.21000,3,3,3,4,4,2,3,2
9998,9999,E344109,f5a68e69-2a60-409b-a92f-ac0847b27db0,2bb491ef5b1beb1fed758cc6885c167a,Quinn,SD,Pennington,57775,44.10354,-102.01590,271,Rural,America/Denver,Outdoor activities/education manager,3,43,29702.32000,Divorced,Male,Yes,19.91043,5,2,1,No,Emergency Admission,No,No,Medium,Yes,No,No,No,Yes,No,No,No,No,Blood Work,63.35690,7644.48300,7781.67800,5,5,3,4,4,3,4,3
9999,10000,I569847,bc482c02-f8c9-4423-99de-3db5e62a18d5,95663a202338000abdf7e09311c2a8a1,Coraopolis,PA,Allegheny,15108,40.49998,-80.19959,41524,Urban,America/New_York,Sports development officer,8,70,62682.63000,Separated,Female,Yes,18.38862,5,0,1,No,Observation Admission,No,No,Low,Yes,Yes,No,Yes,No,No,Yes,No,No,Blood Work,70.85059,7887.55300,11643.19000,4,3,3,2,3,6,4,3

### Part I. Research Question

### A.

### 1.

Readmissions can be a huge problem for hospital systems. According to the data dictionary, Readmissions can result in fines to the health system. The question is; Can potential readmissions be predicted by a group of independent variables?

### 2.

The goal of this analysis will be, given a set of training data points, predict whether or not a patient will be readmitted to the hospital.

### Part II. Method Justification

### B.

### 1.

KNN or k-nearest neighbor is an algorithm that can be used to solve both regression and classificiation problems. KNN uses the idea that data points that are similar will exist close to each other. The idea that similar data points are at a closer distance to each other and thus should be grouped together is at the core of the KNN algorithm. This grouping is assisted by the K variable. K essentially says that a data point and it's K value neighbors should be grouped together. ***

### 2.

KNN is interesting in the fact that it makes no assumptions on the data it is using other than they must all exist in the same feature space. It is a non-parametric algorithm.

### 3.

Listed below are the utilized packages and how they assist in making the analysis possible.
- Pandas - Pandas allows a wide varitey of data analytics processes, it is the main library used to import files such as csv's into a format that Python can easily handle. It is also crucial in the creation of additional dataframes.
- Seaborn - Seaborn is a visualization library that makes beautiful data visualizations.
- MatPlotLib - MatPlotLib is the normal go to visualization library in Python.
- SkLearn - SKLearn is the data workhorse, it contains a variety of easy to use algorithms (such as KNN), it also is used to split a data set into test and training data.

### Part III. Data Preparation

### C.

### 1.

One key preprocessing task is to factorize the dependant variables. This is easy to accomplish using Pandas and Python's lambda functions. Factorizing the variables takes a variable such as Gender and converts it possibly responses to integers. In the example of gender, Male would become 0, Female would become 1, and so on. This makes the algorithm have less to process when it comes to making sense of what each variable represents. The code in Section 3 below shows the process. First, unused columns are removed, then columns whose dtype is object are selected and factorized.

### 2.

In [44]:
modified_df = data.drop(columns=['CaseOrder','Customer_id','Interaction','UID','City','State','County','Zip','Lat','Lng','Population','TimeZone','Job'])

### 3.

### 4.

In [45]:
modified_df.to_csv('C:/Users/gwiza/modified_data.csv')

### Part IV. Analysis

### D.

### 1.

In [46]:
modified_train, modified_test = train_test_split(modified_df, train_size = 0.7, test_size = 0.3, random_state = 100)

In [47]:
y_train = modified_train['ReAdmis']
X_train = modified_train.drop('ReAdmis', axis = 1)
y_test = modified_test['ReAdmis']
X_test = modified_test.drop('ReAdmis', axis = 1)

In [48]:
X_train= oe.fit_transform(X_train)
X_test = oe.transform(X_test)

In [58]:
X_test

array([[ 0.,  4., 20., ...,  2.,  2.,  2.],
       [ 2.,  1., 68., ...,  3.,  2.,  3.],
       [ 2.,  3., 26., ...,  2.,  4.,  2.],
       ...,
       [ 0.,  0.,  8., ...,  0.,  1.,  2.],
       [ 1.,  1., 27., ...,  4.,  2.,  1.],
       [ 2.,  0., 26., ...,  1.,  0.,  2.]])

In [55]:
knn = KNeighborsClassifier(n_neighbors = 14)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=14)

In [56]:
y_pred = knn.predict(X_test)

In [57]:
knn.score(X_test, y_test)

0.6363333333333333

In [53]:
print(cm)

NameError: name 'cm' is not defined

In [54]:
#create new a knn model
knn2 = KNeighborsClassifier()
#create a dictionary of all values we want to test for n_neighbors
param_grid = {'n_neighbors': np.arange(1, 25)}
#use gridsearch to test all values for n_neighbors
knn_gscv = GridSearchCV(knn2, param_grid, cv=5)
#fit model to data
knn_gscv.fit(X_test, y_test)
knn_gscv.best_params_

{'n_neighbors': 14}

### Part V. Data Summary and Implications

### E.

### 1

### 2

### 3

### 4