In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import MinMaxScaler, OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, mean_squared_error
from sklearn.model_selection import cross_val_score
pd.options.display.float_format = '{:.5f}'.format
pd.options.display.max_columns = None

In [2]:
data = pd.read_csv('medical_clean.csv')

In [3]:
data

,CaseOrder,Customer_id,Interaction,UID,City,State,County,Zip,Lat,Lng,Population,Area,TimeZone,Job,Children,Age,Income,Marital,Gender,ReAdmis,VitD_levels,Doc_visits,Full_meals_eaten,vitD_supp,Soft_drink,Initial_admin,HighBlood,Stroke,Complication_risk,Overweight,Arthritis,Diabetes,Hyperlipidemia,BackPain,Anxiety,Allergic_rhinitis,Reflux_esophagitis,Asthma,Services,Initial_days,TotalCharge,Additional_charges,item1,item2,item3,item4,item5,item6,item7,item8
0,1,C412403,8cd49b13-f45a-4b47-a2bd-173ffa932c2f,3a83ddb66e2ae73798bdf1d705dc0932,Eva,AL,Morgan,35621,34.34960,-86.72508,2951,Suburban,America/Chicago,"Psychologist, sport and exercise",1,53,86575.93000,Divorced,Male,No,19.14147,6,0,0,No,Emergency Admission,Yes,No,Medium,No,Yes,Yes,No,Yes,Yes,Yes,No,Yes,Blood Work,10.58577,3726.70286,17939.40342,3,3,2,2,4,3,3,4
1,2,Z919181,d2450b70-0337-4406-bdbb-bc1037f1734c,176354c5eef714957d486009feabf195,Marianna,FL,Jackson,32446,30.84513,-85.22907,11303,Urban,America/Chicago,Community development worker,3,51,46805.99000,Married,Female,No,18.94035,4,2,1,No,Emergency Admission,Yes,No,High,Yes,No,No,No,No,No,No,Yes,No,Intravenous,15.12956,4193.19046,17612.99812,3,4,3,4,4,4,3,3
2,3,F995323,a2057123-abf5-4a2c-abad-8ffe33512562,e19a0fa00aeda885b8a436757e889bc9,Sioux Falls,SD,Minnehaha,57110,43.54321,-96.63772,17125,Suburban,America/Chicago,Chief Executive Officer,3,53,14370.14000,Widowed,Female,No,18.05751,4,1,0,No,Elective Admission,Yes,No,Medium,Yes,No,Yes,No,No,No,No,No,No,Blood Work,4.77218,2434.23422,17505.19246,2,4,4,4,3,4,3,3
3,4,A879973,1dec528d-eb34-4079-adce-0d7a40e82205,cd17d7b6d152cb6f23957346d11c3f07,New Richland,MN,Waseca,56072,43.89744,-93.51479,2162,Suburban,America/Chicago,Early years teacher,0,78,39741.49000,Married,Male,No,16.57686,4,1,0,No,Elective Admission,No,Yes,Medium,No,Yes,No,No,No,No,No,Yes,Yes,Blood Work,1.71488,2127.83042,12993.43735,3,5,5,3,4,5,5,5
4,5,C544523,5885f56b-d6da-43a3-8760-83583af94266,d2f0425877b10ed6bb381f3e2579424a,West Point,VA,King William,23181,37.59894,-76.88958,5287,Rural,America/New_York,Health promotion specialist,1,22,1209.56000,Widowed,Female,No,17.43907,5,0,2,Yes,Elective Admission,No,No,Low,No,No,No,Yes,No,No,Yes,No,No,CT Scan,1.25481,2113.07327,3716.52579,2,1,3,3,5,3,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,B863060,a25b594d-0328-486f-a9b9-0567eb0f9723,39184dc28cc038871912ccc4500049e5,Norlina,NC,Warren,27563,36.42886,-78.23716,4762,Urban,America/New_York,"Programmer, multimedia",2,25,45967.61000,Widowed,Male,No,16.98086,4,2,1,No,Emergency Admission,Yes,No,Medium,No,No,No,No,No,Yes,No,Yes,No,Intravenous,51.56122,6850.94200,8927.64200,3,2,2,3,4,3,4,2
9996,9997,P712040,70711574-f7b1-4a17-b15f-48c54564b70f,3cd124ccd43147404292e883bf9ec55c,Milmay,NJ,Atlantic,8340,39.43609,-74.87302,1251,Urban,America/New_York,"Restaurant manager, fast food",4,87,14983.02000,Widowed,Male,Yes,18.17702,5,0,0,No,Elective Admission,Yes,No,Medium,Yes,Yes,Yes,No,No,No,No,No,Yes,CT Scan,68.66824,7741.69000,28507.15000,3,3,4,2,5,3,4,4
9997,9998,R778890,1d79569d-8e0f-4180-a207-d67ee4527d26,41b770aeee97a5b9e7f69c906a8119d7,Southside,TN,Montgomery,37171,36.36655,-87.29988,532,Rural,America/Chicago,"Psychologist, occupational",3,45,65917.81000,Separated,Female,Yes,17.12907,4,2,0,Yes,Elective Admission,Yes,No,High,Yes,No,No,No,No,Yes,Yes,No,No,Intravenous,70.15418,8276.48100,15281.21000,3,3,3,4,4,2,3,2
9998,9999,E344109,f5a68e69-2a60-409b-a92f-ac0847b27db0,2bb491ef5b1beb1fed758cc6885c167a,Quinn,SD,Pennington,57775,44.10354,-102.01590,271,Rural,America/Denver,Outdoor activities/education manager,3,43,29702.32000,Divorced,Male,Yes,19.91043,5,2,1,No,Emergency Admission,No,No,Medium,Yes,No,No,No,Yes,No,No,No,No,Blood Work,63.35690,7644.48300,7781.67800,5,5,3,4,4,3,4,3
9999,10000,I569847,bc482c02-f8c9-4423-99de-3db5e62a18d5,95663a202338000abdf7e09311c2a8a1,Coraopolis,PA,Allegheny,15108,40.49998,-80.19959,41524,Urban,America/New_York,Sports development officer,8,70,62682.63000,Separated,Female,Yes,18.38862,5,0,1,No,Observation Admission,No,No,Low,Yes,Yes,No,Yes,No,No,Yes,No,No,Blood Work,70.85059,7887.55300,11643.19000,4,3,3,2,3,6,4,3

## Part I: Research Question

### A.

### 1.

With readmission costing hospitals money and time, could a predictive model be effectively used to predict those patients at the highest risk of being readmitted?

### 2.

The main goal of this analysis is to create a model that can accurately predict readmissions based on a number of given independent variables.

## Part II: Model Justification

### B.

### 1.

Random forests are in the simplest terms a group of decision trees. This leads to a variety of positives including reduced chances of overfitting and normally an increase in the models ability to predict more correctly the test data set. Random forests take small samples of our training set to train individual trees, these trees make up a forest, the data for each tree being a small portion of the original data, but picked at random is where the random component comes from. The actual predicition is then made based on the majority count of trees in the voting pool. For the data at hand if 200 trees vote a patient will be readmitted and 30 vote they won't, then the patient will be predicted as a readmit. (z_ai, 2021)

### 2.

With random forests the only assumption is that the data sampling for each tree be representative of the whole data set. (Chatterjee, 2019)

### 3.

Listed below are the utilized packages and how they assist in making the analysis possible.
- Pandas - Pandas allows a wide varitey of data analytics processes, it is the main library used to import files such as csv's into a format that Python can easily handle. It is also crucial in the creation of additional dataframes.
- SkLearn - SKlearn has a multitude of uses from being the home of the algorithm we will be using, to spliting our data into training and test sets, to also giving us our metrics that will be used to judge how well the model performed.

## Part III. Data Preparation

### C.

### 1.

Like most models, Random forests don't have the ability to handle categorical variables in their native form, so to correct this, factorization must occur. Simply put factorizing categorical variables takes strings and converts them into integers. For example, Marital will convert Single, Married, Divorced, and Widowed into corresponding numbers such as 0,1,2,3 respectively. This process allows the model to use the data.

### 2.

### Categorical Variables: 
Marital, 
Gender, 
Soft_drink,
Initial_admin, 
HighBlood,
Stroke,
Complication_risk,
Overweight,
Arthritis,
Diabetes,
Hyperlipidemia,
BackPain,
Anxiety,
Allergic_rhinitis,
Reflux_esophagitis,
Asthma,
Services
### Continuous Variables:  
Children,
Age,
Income,
VitD_levels,
Doc_visits,
Full_meals_eaten,
vitD_supp,
Initial_days,
Total_charges,
Additional_charges

### 3.

The process of prepping this data for analysis is fairly simply due to the nature of it being so clean. First, columns that aren't crucial to the analysis are dropped. Then in the next code block, the categorical variables are factorized. Finally, the data is split into 2 variables, X contains the independent variables and y is the dependent.

In [4]:
clean_data = data.drop(columns=['Area','CaseOrder','Customer_id','Interaction','UID','City','State','County','Zip','Lat','Lng','Population','TimeZone','Job','item1','item2','item3','item4','item5','item6','item7','item8'])

In [5]:
clean_data

,Children,Age,Income,Marital,Gender,ReAdmis,VitD_levels,Doc_visits,Full_meals_eaten,vitD_supp,Soft_drink,Initial_admin,HighBlood,Stroke,Complication_risk,Overweight,Arthritis,Diabetes,Hyperlipidemia,BackPain,Anxiety,Allergic_rhinitis,Reflux_esophagitis,Asthma,Services,Initial_days,TotalCharge,Additional_charges
0,1,53,86575.93000,Divorced,Male,No,19.14147,6,0,0,No,Emergency Admission,Yes,No,Medium,No,Yes,Yes,No,Yes,Yes,Yes,No,Yes,Blood Work,10.58577,3726.70286,17939.40342
1,3,51,46805.99000,Married,Female,No,18.94035,4,2,1,No,Emergency Admission,Yes,No,High,Yes,No,No,No,No,No,No,Yes,No,Intravenous,15.12956,4193.19046,17612.99812
2,3,53,14370.14000,Widowed,Female,No,18.05751,4,1,0,No,Elective Admission,Yes,No,Medium,Yes,No,Yes,No,No,No,No,No,No,Blood Work,4.77218,2434.23422,17505.19246
3,0,78,39741.49000,Married,Male,No,16.57686,4,1,0,No,Elective Admission,No,Yes,Medium,No,Yes,No,No,No,No,No,Yes,Yes,Blood Work,1.71488,2127.83042,12993.43735
4,1,22,1209.56000,Widowed,Female,No,17.43907,5,0,2,Yes,Elective Admission,No,No,Low,No,No,No,Yes,No,No,Yes,No,No,CT Scan,1.25481,2113.07327,3716.52579
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2,25,45967.61000,Widowed,Male,No,16.98086,4,2,1,No,Emergency Admission,Yes,No,Medium,No,No,No,No,No,Yes,No,Yes,No,Intravenous,51.56122,6850.94200,8927.64200
9996,4,87,14983.02000,Widowed,Male,Yes,18.17702,5,0,0,No,Elective Admission,Yes,No,Medium,Yes,Yes,Yes,No,No,No,No,No,Yes,CT Scan,68.66824,7741.69000,28507.15000
9997,3,45,65917.81000,Separated,Female,Yes,17.12907,4,2,0,Yes,Elective Admission,Yes,No,High,Yes,No,No,No,No,Yes,Yes,No,No,Intravenous,70.15418,8276.48100,15281.21000
9998,3,43,29702.32000,Divorced,Male,Yes,19.91043,5,2,1,No,Emergency Admission,No,No,Medium,Yes,No,No,No,Yes,No,No,No,No,Blood Work,63.35690,7644.48300,7781.67800
9999,8,70,62682.63000,Separated,Female,Yes,18.38862,5,0,1,No,Observation Admission,No,No,Low,Yes,Yes,No,Yes,No,No,Yes,No,No,Blood Work,70.85059,7887.55300,11643.19000

In [6]:
cat_columns = clean_data.select_dtypes(['object']).columns
clean_data[cat_columns] = clean_data[cat_columns].apply(lambda x: pd.factorize(x)[0])

In [7]:
clean_data.to_csv('clean_data.csv')

In [8]:
X = clean_data.drop(columns=['ReAdmis'])
y = clean_data['ReAdmis']

## Part IV: Analysis

### D.

### 1.

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X, y,test_size=0.25,random_state=1,stratify=y)

### 2.

The process of analysis for a random forest is simply variable rf is created as an instance of the RandomForestClassifier, then the model is fitted with the training from the train_test_split. Y_pred is created as the predicitions for the dependent variable from the test X values and accuracy scores and Mean Squared Errors are calculated using sklearn metrics.

### 3.

In [10]:
rf = RandomForestRegressor()

In [11]:
rf.fit(X_train,y_train);

In [12]:
y_pred = rf.predict(X_test)

In [13]:
rf.score(X_test, y_test)

0.9357332990725477

In [14]:
mean_squared_error(y_test,y_pred)

0.014926439999999997

In [15]:
cv_scores = cross_val_score(rf, X, y, cv=5)

In [16]:
cv_scores.mean()

0.9282652729383258

## Part V: Data Summary and Implications

### E.

### 1.

In [17]:
print('The accuracy score of the model is  %s' % (rf.score(X_test,y_test)*100))

The accuracy score of the model is  93.57332990725476

The accuracy score of a model can be defined as the model's ability to correctly predict values. The model uses it's fitting to predict values for y_test based on the variables from X_test, those predictions are then checked against y_test's actual values and a score is generated. This model achieved and accuracy score of .934 or 93.4%. (Classification: Accuracy | Machine Learning Crash Course)

In [18]:
print('The mean squared error of the model is  %s' % mean_squared_error(y_test,y_pred))

The mean squared error of the model is  0.014926439999999997

The mean squared error of a model can be defined as, as the name implies a square of the errors. This is most easily graphed, then the distance between the predicition line and the estimated values are squared and the resulting values are added together. SkLearn handles this calculation easily and takes all the heavy lifting and chance for human error. ( Binieli, 2018)

### 2.

With the model generating a high accuracy score and low error score the model is accurate. This implies that the model could essentially be used in real world situations without much cause for concern as long as the data is as clean as our initial set.

### 3.

The main issue with this model would be that if the criteria were to change and the data set were to get larger the model could slow down to a point that it wouldn't work in real time. This could lead to missed opportunities in terms of addressing the need of a model that could work in real time.

### 4.

## References

API Reference. scikit. (n.d.). https://scikit-learn.org/stable/modules/classes.html.  
Binieli, M. (2018, October 8). Machine learning: an introduction to mean squared error and regression lines. freeCodeCamp.org. https://www.freecodecamp.org/news/machine-learning-mean-squared-error-regression-line-c7dde9a26b93/.   
Chatterjee, D. R. (2019, August 26). All the Annoying Assumptions. Medium. https://towardsdatascience.com/all-the-annoying-assumptions-31b55df246c3. 
Google. (n.d.). Classification: Accuracy &nbsp;|&nbsp; Machine Learning Crash Course. Google. https://developers.google.com/machine-learning/crash-course/classification/accuracy. 
z_ai. (2021, March 7). Random Forest Explained. Medium. https://towardsdatascience.com/random-forest-explained-7eae084f3ebe.